import datetime
import pandas as pd
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from nlppreprocess import NLP

#***reading raw data generated by twint scraper***
data = pd.read_csv('Processed_data_input_to_sentiment.csv', encoding='latin1',
                   usecols=["date", "time", "username", "name", "tweet", "likes_count"])

pos = []
neg = []
neu = []
compound = []

nlp = NLP()
data['tweet'] = data['tweet'].apply(nlp.process)
data.to_csv("Temp_StopWords_Removed.csv") # just to check 

#***sentiment analysis using vader sentiment***
sid_obj = SentimentIntensityAnalyzer()
for ind in data.index:
    snt = sid_obj.polarity_scores(data['tweet'][ind])
    pos.append(snt['pos'])
    neg.append(snt['neg'])
    neu.append(snt['neu'])
    compound.append(snt['compound'])
    date = data['date'][ind]
    
    # dataframe loads date as string , so convert string to date , as it is easier to groupby 
    day = date[0:2]
    month = date[3:5]
    year = date[6:]
    data['date'][ind] = datetime.date(int(year), int(month), int(day))

list_of_tuples = list(zip(data['date'], pos, neg, neu, compound))
final_data = pd.DataFrame(list_of_tuples, columns=['Date', 'Positive', 'Negative', 'Neutral', 'Compound'])
final_data = final_data.groupby(['Date'], as_index=False).mean()
final_data.to_csv("Sentiment_Data_Output_of_Step2.csv")
